### ISSUE TITLE
Server fails to start 

### ISSUE THREAD

**Issue by werlend** [1zc/CS2-Pterodactyl#10]
I get this error every time. I guess it could come from a number of reasons.

`container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from 1zc/steamrt3-pterodactyl 
Digest: sha256:24204c5904fee5df91ac4a8abad183a1bd64582b26a3c756e6ae362dfe312cd6 
Status: Image is up to date for ghcr.io/1zc/steamrt3-pterodactyl:latest 
[Pterodactyl Daemon]: Finished pulling Docker container image
/entrypoint.sh: line 5: ip: command not found
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
src/tier0/threadtools.cpp (4197) : Probably deadlock or failure waiting for thread to initialize.
[  0%] Checking for available updates...
assert_20231002074749_5.dmp[18]: Uploading dump (out-of-process)
/tmp/dumps/assert_20231002074749_5.dmp

Thread failed to initialize
src/tier0/threadtools.cpp (4197) : Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
CWorkThreadPool::StartWorkThread: Thread creation failed.
assert_20231002074749_5.dmp[18]: Finished uploading minidump (out-of-process): success = yes

assert_20231002074749_5.dmp[18]: response: Discarded=1

assert_20231002074749_5.dmp[18]: file ''/tmp/dumps/assert_20231002074749_5.dmp'', upload yes: ''Discarded=1''`

**Comment by LukasW1337** [comment]
I actually logged into github just to make an error about this.
I was having the same issues on a host running ubuntu 18.04 - upgrading it to 20.04 solved the issue.

@1zc maybe you can add a warning that it doesn't work on 18.04. I'm not experienced enough to say if other linux distributions  have a required minimum version. But you can add that ubuntu 18.04 doesn't work at least.

**Comment by 1zc** [comment]
Thanks @LukasW1337, I think SteamRT3 doesn't run on anything older than Debian 11 as well - need confirmation on this though 

I will add a section in the ReadME later for OS compatibility so people can refer to it quickly

**Comment by 1zc** [comment]
I've added a list of tested compatible OS to the readme: https://github.com/1zc/CS2-Pterodactyl#frequent-issues
