### ISSUE TITLE
Failed rcon

### ISSUE THREAD

**Issue by ALFREDYTX** [1zc/CS2-Pterodactyl#13]
I just created a dedicated cs2 server but when I put some rcon. command in the game console I get "unable to connect to remote server" and in the server console I get "SV: 'ΛＬＦＲΞＤＲΞＤＹＴＸツ' (tick 23889) OnSimulateUserCommands(), commands starved for 64 ticks, 1000. 0 ms (limit 1000.0 ms) not queuing additional command". Also I already put in the startup -usercon so I got the startup "./game/cs2.sh -dedicated +ip xxx.xxx.xxx.xxx.x -port 27015 +map de_dust2 -usercon". Do you know how to fix it?

**Comment by Javierko** [comment]
Hi,

I had same issue. The problem is probably in the image (steamrt3 ?). I recommend you to use [this egg instead](https://github.com/parkervcp/eggs/pull/2490), it's working fine even with rcon.

**Comment by Ballaual** [comment]
> Hi,
> 
> I had same issue. The problem is probably in the image (steamrt3 and sniper platform). I recommend you to use [this egg instead](https://github.com/parkervcp/eggs/pull/2490), it's working fine even with rcon.

even with that egg rcon might not work as intended when joined the server as the server wont accept the commands. then you can either run the command directly in the server console (without rcon prefix) or use external rcon clients / use rcon_adress IP:PORT and then rcon rcon_password PASS to use your commands from lobby.

**Comment by Javierko** [comment]
> use external rcon clients / use rcon_adress IP:PORT and then rcon rcon_password PASS to use your commands from lobby.

Yes, that's what I'm using. That was the problem with sniper platform (was unable to connect to rcon from client).

**Comment by Ballaual** [comment]
i've updated the egg tonight with some little bugfixes and qol stuff. in the next days i will bring an update for using sourcetv and after this i will work on a option to load workshop maps/collection to the server. if you guys have any further idea or wishes to be implemented let me know! :)

**Comment by Ballaual** [comment]
seems that valve brought a update for 740 app (server files) will test them and update the egg if working well!
https://steamdb.info/app/740/depots/
