### ISSUE TITLE
Can't connect to cs2 server

### ISSUE THREAD

**Issue by HostRK1** [1zc/CS2-Pterodactyl#17]
I have started a csgo server, everything seems to be ok in the console but nobody can't connect to the server (sv_lan is also set to 0).
OS: Ubuntu 20.04
Port is not behind firewall.
Server IP: 138.201.109.66:27015

Server log: https://pastebin.com/LNJWKJ8y
Client log: https://pastebin.com/QwPcfaWc

**Comment by 1zc** [comment]
These logs don't really show anything, make sure the IP is binding correctly on your server. Refer pinned issues.
