### ISSUE TITLE
ip problem

### ISSUE THREAD

**Issue by m4m1s** [1zc/CS2-Pterodactyl#25]
I have servers for CS2, and only the main IP is visible in the Steam browser. The other ones are behaving like the main IP address. How can I resolve this issue? (I can connect to server via "connect".
https://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=185.118.141.74:27015&format=json
https://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=185.118.141.74:27015&format=json
![image](https://github.com/1zc/CS2-Pterodactyl/assets/55399613/7917a1e0-7274-4fa9-b134-9f6a7e74f591)
![image2](https://github.com/1zc/CS2-Pterodactyl/assets/55399613/ede782e5-f3d6-43bb-881c-fa85b8a26fe3)

**Comment by tonkatsuki** [comment]
You closed this issue, I assume you fixed it with the "Force Outgoing IP" feature?
