### ISSUE TITLE
CS2 server can't start 

### ISSUE THREAD

**Issue by sumickk** [1zc/CS2-Pterodactyl#29]
CS2 doesn't start with this errors. Using docker image SteamRT3-Dev. 
DNS using in pterodactyl - 8.8.8.8 and 8.8.4.4 (csgo servers are working fine)

CS2 servers also worked before, but more than a week ago this started
![image](https://github.com/1zc/CS2-Pterodactyl/assets/106545464/40f9e5c5-ea55-42c1-ba67-0a9ba62bc95a)

**Comment by 1zc** [comment]
This is an issue on your end, seems like you can't contact Steam:
1. Make sure you've enabled `Force Outgoing IP` in your egg settings
2. Make sure the IP you've assigned is correct :)

Otherwise, I'd recommend contacting your hosting provider
