### ISSUE TITLE
Server doesnt showing up in Server browser

### ISSUE THREAD

**Issue by lashakaraulashvili** [1zc/CS2-Pterodactyl#32]
Server doesnt showing up in server browser. When adding manually in favorites it works

**Comment by 1zc** [comment]
Do you have a GSLT configured? If it's showing up manually in favourites, it's probably working fine, just make sure you have a GSLT configured

**Comment by lashakaraulashvili** [comment]
Yes, i already added GSLT token 
[](https://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=176.98.43.139)

**Comment by 1zc** [comment]
To be honest, it seems like its responding to A2S queries just fine, so not sure if there's anything really wrong here - maybe you're getting a bit unlucky with it not showing in the public list for you? Either way, likely not an issue with the egg
