### ISSUE TITLE
duplicate files?

### ISSUE THREAD

**Issue by b-reich** [1zc/CS2-Pterodactyl#35]
First, thanks for your egg :)

I use the cs2 egg and I wondering why there is an `csgo` folder in 
`/home/container/csgo`and `/home/container/games/csgo`

Think there could be a bug which install cs in 2 different locations.

Its also re download cs after the initial installing, may the https://github.com/1zc/CS2-Pterodactyl/blob/main/pterodactyl/cs2.json#L33 isnt correct here.

Also the overall file size is a bit to large. `65.67 GiB`

**Comment by b-reich** [comment]
dont why but my default `SRCDS_APPID` was `740`not `740`the install script didnt resepect a change there. I provide an pr for this.

**Comment by pedrotski** [comment]
The APPID doesn't really need to be on a variable, as it's not supposed to be changed from 730.

As for the double installed, I'm trying to figure out the change that's caused that now.

**Comment by 1zc** [comment]
Sorry for the delay, been extremely busy - this is.... odd, not terribly certain why this is happening

Will see what I can find

**Comment by 1zc** [comment]
Can't replicate this anymore, asked someone else to try as well but no dice - just going to close this for now.
