### ISSUE TITLE
Issue with app updating

### ISSUE THREAD

**Issue by ArttuKuikka** [1zc/CS2-Pterodactyl#38]
Hi, every time i try to lauch the app the update fails with message 'Error! App '730' state is 0x602 after update job.'
![image](https://github.com/1zc/CS2-Pterodactyl/assets/75498768/77db6628-9578-463e-a092-5384ae93fa3b)

 i have no idea what is causing this

**Comment by ArttuKuikka** [comment]
This is my stderr.txt content
![image](https://github.com/1zc/CS2-Pterodactyl/assets/75498768/34ef7b94-83e3-47e3-bb68-f5d9f00617d0)

**Comment by 1zc** [comment]
@ArttuKuikka This might be that your server is failing to download the game entirely - I'd say wipe the `Steam` and `steamapps` folders, then try again. If not, I'd say check your network or server and see if there's anything else that might be stopping it (maybe disk is full, etc)
