### ISSUE TITLE
Bugs?

### ISSUE THREAD

**Issue by Truyn** [1zc/CS2-Pterodactyl#43]
Sometimes it happens after an update so that the gameinfo.gi file is erased and the server is updated endlessly every time, if you manually add it, it doesn’t help, even reinstalling. The only thing that saves is to reinstall the server completely

**Comment by 1zc** [comment]
Hi, sorry for the delay - I don't think I've heard of this happening, but if you have any more info on how I can replicate this (I tried but can't seem to), that would be really helpful
