### ISSUE TITLE
steamclient.so doesn't get automatically updated

### ISSUE THREAD

**Issue by Vauff** [1zc/CS2-Pterodactyl#44]
`/.steam/sdk64/steamclient.so` seems to never get automatically updated (see modification date).
![image](https://github.com/1zc/CS2-Pterodactyl/assets/6075172/adbaf3a0-0dc9-42fb-a2e2-0531c85f42da)

However `/steamcmd/linux64/steamclient.so` does.
![image (1)](https://github.com/1zc/CS2-Pterodactyl/assets/6075172/cf10351b-fe38-4880-9cf9-ed1a917b3407)

This has caused issues after todays CS2 update, because Valve seems to now be compiling against a newer `steamclient.so`.
```
[S_API] SteamAPI_Init(): Loaded '/home/container/.steam/sdk64/steamclient.so' OK.  (First tried local 'steamclient.so')
[S_API] SteamAPI_Init(): No SteamClient021
Failed to initialize Steamworks SDK for gameserver.  No SteamClient021
 0 Failed to initialize Steamworks SDK for gameserver.  No SteamClient021
```
Manually copying the updated lib from `/steamcmd/linux64/` to `/.steam/sdk64/` can solve the issue in the short term.

**Comment by LukasW1337** [comment]
It does update if you run the install script, so hitting 'reinstall' under settings fixes the server.

**Comment by 1zc** [comment]
> But for the future. Would this be solved with a symlink?

Maybe, maybe not - I'll take a look as soon as I can

**Comment by 1zc** [comment]
I've updated the docker image's entry point to ensure the `steamclient.so` binaries for sdk32/64 are updated after SteamCMD is done doing whatever it needs to do

I tried using a symlink, but it looks like this doesn't behave as expected - found my servers just failing to find the file at all.

This is now live on the dev Docker images: 
![image](https://github.com/1zc/CS2-Pterodactyl/assets/39123848/e381864e-76d2-45e5-8c49-ace72561f395)

I'll push to the main Docker image soon and close this issue, thanks for the report

**Comment by Truyn** [comment]
Big LIKE!!!
