### ISSUE TITLE
Unable to use steamguard to log in

### ISSUE THREAD

**Issue by GreatSymphonia** [1zc/CS2-Pterodactyl#5]
While attempting to log in, I am blocked by steam guard and I can't seem to be able to register the steam guard code like asked.

![image](https://github.com/1zc/CS2-Pterodactyl/assets/47793265/1281d54d-61b6-4060-919a-1f793a868e99)

**Comment by Jay2k1** [comment]
Worked fine for me (via e-mail). What did *not* work is entering a Steam Guard code from the mobile Steam app.

**Comment by 1zc** [comment]
As mentioned in the ReadMe, you will need Steam Guard disabled for the first-time install to work properly. Past that point, you could use email Steam Guard codes like @Jay2k1 mentioned, but ultimately I recommend making a dummy Steam account, getting CS2 on it, and disabling Steam Guard entirely for use with your server(s)
