### ISSUE TITLE
/entrypoint.sh: line 99: ./game/cs2.sh: No such file or directory

### ISSUE THREAD

**Issue by csd4ni3l** [1zc/CS2-Pterodactyl#51]
The ./game/cs2.sh file doesnt get created. I have enough storage.

**Comment by csd4ni3l** [comment]
There is no "game" directory, but the csgo directory has all of the game files, like with a simple steamcmd install.

**Comment by csd4ni3l** [comment]
@1zc 
![image](https://github.com/user-attachments/assets/e8c86ea5-6907-41d6-a8de-a3360b0d37e3)

**Comment by 1zc** [comment]
Could I see what's inside `csgo` very quickly? I'll take a better look later, currently away for a little bit

**Comment by csd4ni3l** [comment]
it is 32gb, so the base game. Here are screenshots, there are much more vpk files, i just didnt want to screenshot all of them:
![image](https://github.com/user-attachments/assets/99be5ba4-f72d-4015-8886-8f59d2dcc585)
![image](https://github.com/user-attachments/assets/99ca412a-c551-4767-b628-a654c4e67812)
![image](https://github.com/user-attachments/assets/39862b8c-4885-4b59-a967-2aed3608be1e)
![image](https://github.com/user-attachments/assets/edcce6bd-a7ad-4bc1-bee6-e5e8d80ba7c8)

**Comment by csd4ni3l** [comment]
I am using the SteamRT3 docker image. Should i switch to beta or dev?

**Comment by 1zc** [comment]
I don't think the docker image is to blame here, but it looks like your server has installed CSGO, not CS2? Which is even weirder lol, did you use the CS2 egg?

**Comment by csd4ni3l** [comment]
Yes, i downloaded cs2.json

**Comment by csd4ni3l** [comment]
[cs2.json](https://github.com/user-attachments/files/16608371/cs2.json)

**Comment by csd4ni3l** [comment]
Well, i had csgo on it before, but deleted all files, so i will try a clean server install.

**Comment by 1zc** [comment]
Okay try that and let me know - wipe the files, use the "Reinstall" option in the Pterodactyl admin panel. If you do that and it still installs CS:GO, let me know and I'll look into the egg

**Comment by csd4ni3l** [comment]
Last thing to ask, i have a lot of ports forwarded, which of these is actually needed? cause srcds lists a lot
![image](https://github.com/user-attachments/assets/901b9aee-dfb3-4844-8eca-8f8d69d011f1)

**Comment by csd4ni3l** [comment]
Okay, remake worked, now i have a game directory. what you said was what i did before, changing image, then reinstalling, but that didnt work. Now a complete server remake works, and now i have the game directory.

**Comment by csd4ni3l** [comment]
Launcher Error: A CPU that supports the SSE4.2 processor feature is required.

well, nevermind then, i wont run this. My VPS doesnt support this cpu instruction it seems like. Thanks for the help tho.
