### ISSUE TITLE
Certificate expires

### ISSUE THREAD

**Issue by deLuXe83** [1zc/CS2-Pterodactyl#7]
Hey,
I am getting "spam" outputs in console:
`Certificate expires in 47h50m at 1696184404 (current time 1696012203), will renew in 45h50m`

Any ideas about it?

Thank you very much!

**Comment by 1zc** [comment]
Hi, this isn't an issue and can safely be ignored. For now, you'll just have to deal with the spam, maybe in the future as modding develops further, there will be a way to hide the spam. 😄
