### ISSUE TITLE
CS2 Update Problem

### ISSUE THREAD

**Issue by exababy** [1zc/CS2-Pterodactyl#8]
I restart the server but it doesn't update.

![image](https://github.com/1zc/CS2-Pterodactyl/assets/44870116/ac70ac9f-5beb-4104-81d7-bdc548edde36)

**Comment by 1zc** [comment]
> `ERROR! Password check for AppId 730 returned error Failure.`

Looks like you're failing to log into Steam, have you tried checking the password you're using?

**Comment by exababy** [comment]
It was fixed by deleting the steamcmd beta.
