### ISSUE TITLE
How to set public ip

### ISSUE THREAD

**Issue by Dilyar23** [1zc/CS2-Pterodactyl#9]
How can I set up a public IP? I used to use +net_public_adr, but it doesn't work anymore. I have 4 game servers on different IPs.

**Comment by JMorell** [comment]
I have activated the Force Outgoing IP within the egg configuration and it has worked.

**Comment by JMorell** [comment]
I have activated the Force Outgoing IP within the egg configuration and it has worked.

**Comment by 1zc** [comment]
Unfortunately, the game seems to ignore `net_public_addr` as well, so you'll have to do what @JMorell suggested temporarily - maybe something that'll be solved as updates roll out for the game. 

If you're facing this issue and are not in the `host` networking mode on Pterodactyl, you may have to investigate SNAT if the setting mentioned above doesn't work for you. 

I'll wait and update the README after a few days, thanks everyone (including the others on Discord)

**Comment by 1zc** [comment]
[Frequent Errors](https://github.com/1zc/CS2-Pterodactyl#frequent-issues)
